SELECT *
FROM ppt.agency_higher_ed_prime_cert_summary
WHERE agency_name NOT IN (
  'Arts Commission',
  'Board of Industrial Insurance Appeals',
  'Board of Tax Appeals',
  'Center for Childhood Deaf and Hard of Hearing Youth',
  'Commission on African American Affairs',
  'Commission on Asian Pacific American Affairs',
  'Commission on Hispanic Affairs',
  'County Road Administration Board',
  'Criminal Justice Training Commission',
  'Department of Agriculture',
  'Department of Archaeology and Historic Preservation',
  'Department of Children, Youth and Families',
  'Department of Commerce',
  'Department of Corrections',
  'Department of Ecology',
  'Department of Enterprise Services',
  'Department of Financial Institutions',
  'Department of Fish and Wildlife',
  'Department of Health',
  'Department of Labor and Industries',
  'Department of Licensing',
  'Department of Natural Resources',
  'Department of Retirement Systems',
  'Department of Revenue',
  'Department of Social and Health Services',
  'Department of Transportation',
  'Department of Veteran''s Affairs',
  'Employment Security Department',
  'Energy Facility Site Evaluation Council',
  'Environmental and Land Use Hearings Office',
  'Gambling Commission',
  'Governor''s Office of Indian Affairs',
  'Health Care Authority',
  'Horse Racing Commission',
  'Human Rights Commission',
  'Liquor and Cannabis Board',
  'Lottery Commission',
  'Military Department',
  'Office of Administrative Hearings',
  'Office of Financial Management',
  'Office of Independent Investigations',
  'Office of Minority and Women''s Business Enterprises',
  'Office of the Attorney General',
  'Office of the Governor',
  'Office of the Insurance Commissioner',
  'Office of the Secretary of State',
  'Office of the State Treasurer',
  'Parks and Recreation Commission',
  'Public Disclosure Commission',
  'Public Employment Relations Commission',
  'Puget Sound Partnership',
  'Recreation and Conservation Funding Board',
  'Services for the Blind',
  'Office of the State Auditor',
  'State Board of Accountancy',
  'State Conservation Commission',
  'Superintendent of Public Instruction',
  'Traffic Safety Commission',
  'Transportation Improvement Board',
  'Utilities and Transportation Commission/Transportation Commission',
  'Pollution Liability Insurance Agency',
  'Washington State Patrol',
  'Washington State School for the Blind',
  'Washington Student Achievement Council',
  'Washington Technology Services',
  'Workforce Training and Education Coordinating Board'
);